version: '3.8'
volumes:
  database:
services:
  mongo:
    image: mongo:6.0
    container_name: mongo-6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 789789
    volumes:
      - database:/var/lib/mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 789789
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
